apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-local-pvc
  namespace: expense-tracker-ns
spec:
  accessModes:
      - ReadWriteOnce
  resources:
      requests:
          storage: 300Mi
  storageClassName: manual